const NEXT_PUBLIC_SYSTEM_NAME = process.env.NEXT_PUBLIC_SYSTEM_NAME ?? "Small Library System";
const NEXT_PUBLIC_SYSTEM_NAME_SHORT = process.env.NEXT_PUBLIC_SYSTEM_NAME_SHORT ?? "SLS";
const NEXT_PUBLIC_SYSTEM_DESCRIPTION =
    process.env.NEXT_PUBLIC_SYSTEM_DESCRIPTION ?? "QRコードで所蔵物を管理するシステム";
const NEXT_PUBLIC_API_BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL ?? "http://localhost:8080";

export {
    NEXT_PUBLIC_SYSTEM_NAME,
    NEXT_PUBLIC_SYSTEM_NAME_SHORT,
    NEXT_PUBLIC_SYSTEM_DESCRIPTION,
    NEXT_PUBLIC_API_BASE_URL,
};
