const NEXT_PUBLIC_SYSTEM_NAME = process.env.NEXT_PUBLIC_SYSTEM_NAME ?? "SmallLibrarySystem";
const NEXT_PUBLIC_SYSTEM_NAME_SHORT = process.env.NEXT_PUBLIC_SYSTEM_NAME_SHORT ?? "蔵書管理";
const NEXT_PUBLIC_SYSTEM_MANAGE_ITEM = process.env.NEXT_PUBLIC_SYSTEM_MANAGE_ITEM ?? "蔵書";
const NEXT_PUBLIC_SYSTEM_DESCRIPTION = process.env.NEXT_PUBLIC_SYSTEM_DESCRIPTION ?? "QRコードを用いて物品を管理するシステムです。";
const NEXT_PUBLIC_SYSTEM_HOST = process.env.NEXT_PUBLIC_SYSTEM_HOST ?? "http://localhost:3000";

const NEXT_PUBLIC_MAX_HISTORY_COUNT = process.env.NEXT_PUBLIC_MAX_HISTORY_COUNT ?? 10;

const ADMIN_PASSWORD = process.env.ADMIN_PASSWORD ?? "admin";

export {
    NEXT_PUBLIC_SYSTEM_NAME,
    NEXT_PUBLIC_SYSTEM_NAME_SHORT,
    NEXT_PUBLIC_SYSTEM_MANAGE_ITEM,
    NEXT_PUBLIC_SYSTEM_DESCRIPTION,
    NEXT_PUBLIC_SYSTEM_HOST,

    NEXT_PUBLIC_MAX_HISTORY_COUNT,

    ADMIN_PASSWORD,
}